spring.application.name=finance-control
spring.datasource.url=jdbc:postgresql://localhost:5432/finance-control
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.open-in-view=false

